### ISSUE TITLE
Charset utf8 for file.

### ISSUE THREAD

**Issue by h4kuna** [Kdyby/Curl#22]
I must check if is need set the charset for uploaded files.

https://github.com/h4kuna/Curl/blob/master/src/Kdyby/Curl/CurlWrapper.php#L394

**Comment by fprochazka** [comment]
I'm sorry, but I don't understand.

**Comment by h4kuna** [comment]
To forked branch I can not write issue. Assigne me :) A look at later.

This mean 'Content-Type: multipart/form-data; charset=utf8' if is nesesary.

**Comment by h4kuna** [comment]
It works fine.
