### ISSUE TITLE
Empty post throws BadStatusException exception

### ISSUE THREAD

**Issue by Zarganwar** [Kdyby/Curl#23]
Hi,
why

```php
$curl->post('');
or $curl->post(array());
```

```
Throws: Kdyby\Curl\BadStatusException #413
413 Request Entity Too Large
```

Empty post isn't prohibited usage or?

Thx a lot for answer.

**Comment by fprochazka** [comment]
Hi, this is an error that is thrown by server when you send it too much data. I have no idea how you've managed that :)
