### ISSUE TITLE
FileLogger fails when response contains some header multiple times

### ISSUE THREAD

**Issue by janedbal** [Kdyby/Curl#28]
Following code:

```php
$request = new Request('https://www.ppl.cz/IEGate/IEGate.asmx');
$request->setCertificationVerify(FALSE); // intermediate cert not provided

$sender = new CurlSender();
$sender->setLogger(new FileLogger());
$sender->send($request);
```

fails with ```Array to string conversion``` on [this line](https://github.com/Kdyby/Curl/blob/7a65bfa5e2f05ff264e6186d1a91cf76a634d58a/src/Kdyby/Curl/Diagnostics/FileLogger.php#L87), because header ```X-Powered-By``` contains array.

```
"X-Powered-By" => array (3)
0 => "ASP.NET"
1 => "ARR/2.5"
2 => "ASP.NET"
```

See

```sh
$ curl --head -k https://www.ppl.cz/IEGate/IEGate.asmx
```

**Comment by fprochazka** [comment]
I'm not really using that class, so its very unlikely that I will fix it any time soon. Can you send a pullrq please?

**Comment by janedbal** [comment]
Actually, I'm not using it too. I just met it in my own logger and checked if the same bug is present in your library. Not sure if I find time for PR...
