### ISSUE TITLE
Response normalization fails.

### ISSUE THREAD

**Issue by bitcont** [Kdyby/Curl#30]
``` php
$request = new Request("http://www.praha6.cz/tabule/?vynechat=25");
return $request->get()->getResponse();
```

Returns an empty string due to this line in Nette\Utils\Strings::normalize:
``` php
// remove control characters; leave \t + \n
$s = preg_replace('#[\x00-\x08\x0B-\x1F\x7F-\x9F]+#u', '', $s);
```

**Comment by fprochazka** [comment]
What do you propose?

**Comment by bitcont** [comment]
I believe this should be fixed in the [nette/utils](https://github.com/nette/utils) package. I'll open the issue there and reference it here (when/if I have time). Ok?

**Comment by fprochazka** [comment]
:+1:
