### ISSUE TITLE
FileLogger uses Nette\Utils\Finder not required by composer

### ISSUE THREAD

**Issue by janedbal** [Kdyby/Curl#35]
Finder has its own package even though it is in ```Nette\Utils``` namespace.

**Comment by TomasVotruba** [comment]
I guess you can send PR for this easily.

**Comment by janedbal** [comment]
Yes, but there is also [usage of php-generator](https://github.com/Kdyby/Curl/blob/a8a501454d5151eb16ef964df84da2684a3ec3d5/src/Kdyby/Curl/Diagnostics/FileLogger.php#L71) in FileLogger (therefore we need two dependencies just for this class) and there is also bug #27 and bug #28. Maybe whole FileLogger should be refactored, but Filip abandoned this package in a8a501454d5151eb16ef964df84da2684a3ec3d5 :(

**Comment by TomasVotruba** [comment]
Oh, good to know. Use the package or make your own fork.

I guess abandoned package means no more development.
